title: Data Science Adjacent Stuff
author: eldalsgaard
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Something something descriptive
theme: minimal

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  eldalsgaard # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
